/*

 HOUSETILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 83

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __HouseTiles_h_INCLUDE
#define __HouseTiles_h_INCLUDE

/* Bank of tiles. */
#define HouseTilesBank 0
/* Start of tile array. */
extern const unsigned char HouseTiles[];

#endif

/* End of HOUSETILES.H */
