//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_AttributionIllustration_H
#define METASPRITE_AttributionIllustration_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define AttributionIllustration_TILE_ORIGIN 0
#define AttributionIllustration_TILE_W 8
#define AttributionIllustration_TILE_H 8
#define AttributionIllustration_WIDTH 8
#define AttributionIllustration_HEIGHT 8
#define AttributionIllustration_TILE_COUNT 215
#define AttributionIllustration_PALETTE_COUNT 1
#define AttributionIllustration_COLORS_PER_PALETTE 4
#define AttributionIllustration_TOTAL_COLORS 4
#define AttributionIllustration_MAP_ATTRIBUTES 0

BANKREF_EXTERN(AttributionIllustration)

extern const palette_color_t AttributionIllustration_palettes[4];
extern const uint8_t AttributionIllustration_tiles[3440];

extern const unsigned char AttributionIllustration_map[360];
#define AttributionIllustration_map_attributes AttributionIllustration_map

#endif
