//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_BeatGameIllustration_H
#define METASPRITE_BeatGameIllustration_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define BeatGameIllustration_TILE_ORIGIN 64
#define BeatGameIllustration_TILE_W 8
#define BeatGameIllustration_TILE_H 8
#define BeatGameIllustration_WIDTH 8
#define BeatGameIllustration_HEIGHT 8
#define BeatGameIllustration_TILE_COUNT 74
#define BeatGameIllustration_PALETTE_COUNT 1
#define BeatGameIllustration_COLORS_PER_PALETTE 4
#define BeatGameIllustration_TOTAL_COLORS 4
#define BeatGameIllustration_MAP_ATTRIBUTES 0

BANKREF_EXTERN(BeatGameIllustration)

extern const palette_color_t BeatGameIllustration_palettes[4];
extern const uint8_t BeatGameIllustration_tiles[1184];

extern const unsigned char BeatGameIllustration_map[360];
#define BeatGameIllustration_map_attributes BeatGameIllustration_map

#endif
