//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_BeatLevel2Illustration_H
#define METASPRITE_BeatLevel2Illustration_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define BeatLevel2Illustration_TILE_ORIGIN 64
#define BeatLevel2Illustration_TILE_W 8
#define BeatLevel2Illustration_TILE_H 8
#define BeatLevel2Illustration_WIDTH 8
#define BeatLevel2Illustration_HEIGHT 8
#define BeatLevel2Illustration_TILE_COUNT 211
#define BeatLevel2Illustration_PALETTE_COUNT 1
#define BeatLevel2Illustration_COLORS_PER_PALETTE 4
#define BeatLevel2Illustration_TOTAL_COLORS 4
#define BeatLevel2Illustration_MAP_ATTRIBUTES 0

BANKREF_EXTERN(BeatLevel2Illustration)

extern const palette_color_t BeatLevel2Illustration_palettes[4];
extern const uint8_t BeatLevel2Illustration_tiles[3376];

extern const unsigned char BeatLevel2Illustration_map[360];
#define BeatLevel2Illustration_map_attributes BeatLevel2Illustration_map

#endif
