//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_BeatLevel1Illustration_H
#define METASPRITE_BeatLevel1Illustration_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define BeatLevel1Illustration_TILE_ORIGIN 0
#define BeatLevel1Illustration_TILE_W 8
#define BeatLevel1Illustration_TILE_H 8
#define BeatLevel1Illustration_WIDTH 8
#define BeatLevel1Illustration_HEIGHT 8
#define BeatLevel1Illustration_TILE_COUNT 129
#define BeatLevel1Illustration_PALETTE_COUNT 1
#define BeatLevel1Illustration_COLORS_PER_PALETTE 4
#define BeatLevel1Illustration_TOTAL_COLORS 4
#define BeatLevel1Illustration_MAP_ATTRIBUTES 0

BANKREF_EXTERN(BeatLevel1Illustration)

extern const palette_color_t BeatLevel1Illustration_palettes[4];
extern const uint8_t BeatLevel1Illustration_tiles[2064];

extern const unsigned char BeatLevel1Illustration_map[360];
#define BeatLevel1Illustration_map_attributes BeatLevel1Illustration_map

#endif
