//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_BeatLevelIllustration_H
#define METASPRITE_BeatLevelIllustration_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define BeatLevelIllustration_TILE_ORIGIN 64
#define BeatLevelIllustration_TILE_W 8
#define BeatLevelIllustration_TILE_H 8
#define BeatLevelIllustration_WIDTH 8
#define BeatLevelIllustration_HEIGHT 8
#define BeatLevelIllustration_TILE_COUNT 163
#define BeatLevelIllustration_PALETTE_COUNT 1
#define BeatLevelIllustration_COLORS_PER_PALETTE 4
#define BeatLevelIllustration_TOTAL_COLORS 4
#define BeatLevelIllustration_MAP_ATTRIBUTES 0

BANKREF_EXTERN(BeatLevelIllustration)

extern const palette_color_t BeatLevelIllustration_palettes[4];
extern const uint8_t BeatLevelIllustration_tiles[2608];

extern const unsigned char BeatLevelIllustration_map[360];
#define BeatLevelIllustration_map_attributes BeatLevelIllustration_map

#endif
