//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ending02_H
#define METASPRITE_ending02_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ending02_TILE_ORIGIN 0
#define ending02_TILE_W 8
#define ending02_TILE_H 8
#define ending02_WIDTH 8
#define ending02_HEIGHT 8
#define ending02_TILE_COUNT 219
#define ending02_PALETTE_COUNT 1
#define ending02_COLORS_PER_PALETTE 4
#define ending02_TOTAL_COLORS 4
#define ending02_MAP_ATTRIBUTES 0

BANKREF_EXTERN(ending02)

extern const palette_color_t ending02_palettes[4];
extern const uint8_t ending02_tiles[3504];

extern const unsigned char ending02_map[360];
#define ending02_map_attributes ending02_map

#endif
