//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ending01_H
#define METASPRITE_ending01_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ending01_TILE_ORIGIN 0
#define ending01_TILE_W 8
#define ending01_TILE_H 8
#define ending01_WIDTH 8
#define ending01_HEIGHT 8
#define ending01_TILE_COUNT 235
#define ending01_PALETTE_COUNT 1
#define ending01_COLORS_PER_PALETTE 4
#define ending01_TOTAL_COLORS 4
#define ending01_MAP_ATTRIBUTES 0

BANKREF_EXTERN(ending01)

extern const palette_color_t ending01_palettes[4];
extern const uint8_t ending01_tiles[3760];

extern const unsigned char ending01_map[360];
#define ending01_map_attributes ending01_map

#endif
