//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ending03_H
#define METASPRITE_ending03_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ending03_TILE_ORIGIN 0
#define ending03_TILE_W 8
#define ending03_TILE_H 8
#define ending03_WIDTH 8
#define ending03_HEIGHT 8
#define ending03_TILE_COUNT 149
#define ending03_PALETTE_COUNT 1
#define ending03_COLORS_PER_PALETTE 4
#define ending03_TOTAL_COLORS 4
#define ending03_MAP_ATTRIBUTES 0

BANKREF_EXTERN(ending03)

extern const palette_color_t ending03_palettes[4];
extern const uint8_t ending03_tiles[2384];

extern const unsigned char ending03_map[360];
#define ending03_map_attributes ending03_map

#endif
