//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_GBCompoIllustration_H
#define METASPRITE_GBCompoIllustration_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define GBCompoIllustration_TILE_ORIGIN 0
#define GBCompoIllustration_TILE_W 8
#define GBCompoIllustration_TILE_H 8
#define GBCompoIllustration_WIDTH 8
#define GBCompoIllustration_HEIGHT 8
#define GBCompoIllustration_TILE_COUNT 69
#define GBCompoIllustration_PALETTE_COUNT 1
#define GBCompoIllustration_COLORS_PER_PALETTE 4
#define GBCompoIllustration_TOTAL_COLORS 4
#define GBCompoIllustration_MAP_ATTRIBUTES 0

BANKREF_EXTERN(GBCompoIllustration)

extern const palette_color_t GBCompoIllustration_palettes[4];
extern const uint8_t GBCompoIllustration_tiles[1104];

extern const unsigned char GBCompoIllustration_map[360];
#define GBCompoIllustration_map_attributes GBCompoIllustration_map

#endif
