//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Intro1Illustration1_H
#define METASPRITE_Intro1Illustration1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Intro1Illustration1_TILE_ORIGIN 0
#define Intro1Illustration1_TILE_W 8
#define Intro1Illustration1_TILE_H 8
#define Intro1Illustration1_WIDTH 160
#define Intro1Illustration1_HEIGHT 72
#define Intro1Illustration1_TILE_COUNT 67
#define Intro1Illustration1_PALETTE_COUNT 1
#define Intro1Illustration1_COLORS_PER_PALETTE 4
#define Intro1Illustration1_TOTAL_COLORS 4
#define Intro1Illustration1_MAP_ATTRIBUTES 0

BANKREF_EXTERN(Intro1Illustration1)

extern const palette_color_t Intro1Illustration1_palettes[4];
extern const uint8_t Intro1Illustration1_tiles[1072];

extern const unsigned char Intro1Illustration1_map[180];
#define Intro1Illustration1_map_attributes Intro1Illustration1_map

#endif
