//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Intro3Illustration_H
#define METASPRITE_Intro3Illustration_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Intro3Illustration_TILE_ORIGIN 0
#define Intro3Illustration_TILE_W 8
#define Intro3Illustration_TILE_H 8
#define Intro3Illustration_WIDTH 160
#define Intro3Illustration_HEIGHT 144
#define Intro3Illustration_TILE_COUNT 154
#define Intro3Illustration_PALETTE_COUNT 1
#define Intro3Illustration_COLORS_PER_PALETTE 4
#define Intro3Illustration_TOTAL_COLORS 4
#define Intro3Illustration_MAP_ATTRIBUTES 0

BANKREF_EXTERN(Intro3Illustration)

extern const palette_color_t Intro3Illustration_palettes[4];
extern const uint8_t Intro3Illustration_tiles[2464];

extern const unsigned char Intro3Illustration_map[360];
#define Intro3Illustration_map_attributes Intro3Illustration_map

#endif
