//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Intro2Illustration1_H
#define METASPRITE_Intro2Illustration1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Intro2Illustration1_TILE_ORIGIN 0
#define Intro2Illustration1_TILE_W 8
#define Intro2Illustration1_TILE_H 8
#define Intro2Illustration1_WIDTH 160
#define Intro2Illustration1_HEIGHT 24
#define Intro2Illustration1_TILE_COUNT 32
#define Intro2Illustration1_PALETTE_COUNT 1
#define Intro2Illustration1_COLORS_PER_PALETTE 4
#define Intro2Illustration1_TOTAL_COLORS 4
#define Intro2Illustration1_MAP_ATTRIBUTES 0

BANKREF_EXTERN(Intro2Illustration1)

extern const palette_color_t Intro2Illustration1_palettes[4];
extern const uint8_t Intro2Illustration1_tiles[512];

extern const unsigned char Intro2Illustration1_map[60];
#define Intro2Illustration1_map_attributes Intro2Illustration1_map

#endif
