//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Intro1Illustration2_H
#define METASPRITE_Intro1Illustration2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Intro1Illustration2_TILE_ORIGIN 67
#define Intro1Illustration2_TILE_W 8
#define Intro1Illustration2_TILE_H 8
#define Intro1Illustration2_WIDTH 160
#define Intro1Illustration2_HEIGHT 72
#define Intro1Illustration2_TILE_COUNT 94
#define Intro1Illustration2_PALETTE_COUNT 1
#define Intro1Illustration2_COLORS_PER_PALETTE 4
#define Intro1Illustration2_TOTAL_COLORS 4
#define Intro1Illustration2_MAP_ATTRIBUTES 0

BANKREF_EXTERN(Intro1Illustration2)

extern const palette_color_t Intro1Illustration2_palettes[4];
extern const uint8_t Intro1Illustration2_tiles[1504];

extern const unsigned char Intro1Illustration2_map[180];
#define Intro1Illustration2_map_attributes Intro1Illustration2_map

#endif
