//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Intro2Illustration2_H
#define METASPRITE_Intro2Illustration2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Intro2Illustration2_TILE_ORIGIN 32
#define Intro2Illustration2_TILE_W 8
#define Intro2Illustration2_TILE_H 8
#define Intro2Illustration2_WIDTH 160
#define Intro2Illustration2_HEIGHT 144
#define Intro2Illustration2_TILE_COUNT 93
#define Intro2Illustration2_PALETTE_COUNT 1
#define Intro2Illustration2_COLORS_PER_PALETTE 4
#define Intro2Illustration2_TOTAL_COLORS 4
#define Intro2Illustration2_MAP_ATTRIBUTES 0

BANKREF_EXTERN(Intro2Illustration2)

extern const palette_color_t Intro2Illustration2_palettes[4];
extern const uint8_t Intro2Illustration2_tiles[1488];

extern const unsigned char Intro2Illustration2_map[360];
#define Intro2Illustration2_map_attributes Intro2Illustration2_map

#endif
