//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_TitleScreenIllustration_H
#define METASPRITE_TitleScreenIllustration_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define TitleScreenIllustration_TILE_ORIGIN 0
#define TitleScreenIllustration_TILE_W 8
#define TitleScreenIllustration_TILE_H 8
#define TitleScreenIllustration_WIDTH 8
#define TitleScreenIllustration_HEIGHT 8
#define TitleScreenIllustration_TILE_COUNT 201
#define TitleScreenIllustration_PALETTE_COUNT 1
#define TitleScreenIllustration_COLORS_PER_PALETTE 4
#define TitleScreenIllustration_TOTAL_COLORS 4
#define TitleScreenIllustration_MAP_ATTRIBUTES 0

BANKREF_EXTERN(TitleScreenIllustration)

extern const palette_color_t TitleScreenIllustration_palettes[4];
extern const uint8_t TitleScreenIllustration_tiles[3216];

extern const unsigned char TitleScreenIllustration_map[360];
#define TitleScreenIllustration_map_attributes TitleScreenIllustration_map

#endif
