//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_TutorialIllustration2_H
#define METASPRITE_TutorialIllustration2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define TutorialIllustration2_TILE_ORIGIN 65
#define TutorialIllustration2_TILE_W 8
#define TutorialIllustration2_TILE_H 8
#define TutorialIllustration2_WIDTH 160
#define TutorialIllustration2_HEIGHT 144
#define TutorialIllustration2_TILE_COUNT 48
#define TutorialIllustration2_PALETTE_COUNT 1
#define TutorialIllustration2_COLORS_PER_PALETTE 4
#define TutorialIllustration2_TOTAL_COLORS 4
#define TutorialIllustration2_MAP_ATTRIBUTES 0

BANKREF_EXTERN(TutorialIllustration2)

extern const palette_color_t TutorialIllustration2_palettes[4];
extern const uint8_t TutorialIllustration2_tiles[768];

extern const unsigned char TutorialIllustration2_map[360];
#define TutorialIllustration2_map_attributes TutorialIllustration2_map

#endif
