//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_TutorialIllustration_H
#define METASPRITE_TutorialIllustration_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define TutorialIllustration_TILE_ORIGIN 0
#define TutorialIllustration_TILE_W 8
#define TutorialIllustration_TILE_H 8
#define TutorialIllustration_WIDTH 160
#define TutorialIllustration_HEIGHT 144
#define TutorialIllustration_TILE_COUNT 72
#define TutorialIllustration_PALETTE_COUNT 1
#define TutorialIllustration_COLORS_PER_PALETTE 4
#define TutorialIllustration_TOTAL_COLORS 4
#define TutorialIllustration_MAP_ATTRIBUTES 0

BANKREF_EXTERN(TutorialIllustration)

extern const palette_color_t TutorialIllustration_palettes[4];
extern const uint8_t TutorialIllustration_tiles[1152];

extern const unsigned char TutorialIllustration_map[360];
#define TutorialIllustration_map_attributes TutorialIllustration_map

#endif
