//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_TutorialIllustration1_H
#define METASPRITE_TutorialIllustration1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define TutorialIllustration1_TILE_ORIGIN 0
#define TutorialIllustration1_TILE_W 8
#define TutorialIllustration1_TILE_H 8
#define TutorialIllustration1_WIDTH 160
#define TutorialIllustration1_HEIGHT 72
#define TutorialIllustration1_TILE_COUNT 65
#define TutorialIllustration1_PALETTE_COUNT 3
#define TutorialIllustration1_COLORS_PER_PALETTE 4
#define TutorialIllustration1_TOTAL_COLORS 12
#define TutorialIllustration1_MAP_ATTRIBUTES 0

BANKREF_EXTERN(TutorialIllustration1)

extern const palette_color_t TutorialIllustration1_palettes[12];
extern const uint8_t TutorialIllustration1_tiles[1040];

extern const unsigned char TutorialIllustration1_map[180];
#define TutorialIllustration1_map_attributes TutorialIllustration1_map

#endif
