/*

 LEVEL1MMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\Projects\Gameboy\MirrorGB\Assets\Raw Tiles\HouseMirrorTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Level1MMap_h_INCLUDE
#define __Level1MMap_h_INCLUDE

#define Level1MMapWidth 32
#define Level1MMapHeight 32
#define Level1MMapBank 0

extern const unsigned char Level1MMap[];

#endif

/* End of LEVEL1MMAP.H */
