//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_HUDTeeth_H
#define METASPRITE_HUDTeeth_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define HUDTeeth_TILE_ORIGIN 0
#define HUDTeeth_TILE_W 8
#define HUDTeeth_TILE_H 16
#define HUDTeeth_WIDTH 32
#define HUDTeeth_HEIGHT 16
#define HUDTeeth_TILE_COUNT 24
#define HUDTeeth_PALETTE_COUNT 1
#define HUDTeeth_COLORS_PER_PALETTE 4
#define HUDTeeth_TOTAL_COLORS 4
#define HUDTeeth_PIVOT_X 16
#define HUDTeeth_PIVOT_Y 8
#define HUDTeeth_PIVOT_W 0
#define HUDTeeth_PIVOT_H 0

BANKREF_EXTERN(HUDTeeth)

extern const palette_color_t HUDTeeth_palettes[4];
extern const uint8_t HUDTeeth_tiles[384];

extern const metasprite_t* const HUDTeeth_metasprites[3];

#endif
