//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_NPCBald_H
#define METASPRITE_NPCBald_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define NPCBald_TILE_ORIGIN 0
#define NPCBald_TILE_W 8
#define NPCBald_TILE_H 8
#define NPCBald_WIDTH 16
#define NPCBald_HEIGHT 16
#define NPCBald_TILE_COUNT 25
#define NPCBald_PALETTE_COUNT 1
#define NPCBald_COLORS_PER_PALETTE 4
#define NPCBald_TOTAL_COLORS 4
#define NPCBald_PIVOT_X 8
#define NPCBald_PIVOT_Y 8
#define NPCBald_PIVOT_W 0
#define NPCBald_PIVOT_H 0

BANKREF_EXTERN(NPCBald)

extern const palette_color_t NPCBald_palettes[4];
extern const uint8_t NPCBald_tiles[400];

extern const metasprite_t* const NPCBald_metasprites[9];

#endif
