//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_NPCgirl_H
#define METASPRITE_NPCgirl_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define NPCgirl_TILE_ORIGIN 0
#define NPCgirl_TILE_W 8
#define NPCgirl_TILE_H 8
#define NPCgirl_WIDTH 16
#define NPCgirl_HEIGHT 16
#define NPCgirl_TILE_COUNT 26
#define NPCgirl_PALETTE_COUNT 1
#define NPCgirl_COLORS_PER_PALETTE 4
#define NPCgirl_TOTAL_COLORS 4
#define NPCgirl_PIVOT_X 8
#define NPCgirl_PIVOT_Y 8
#define NPCgirl_PIVOT_W 0
#define NPCgirl_PIVOT_H 0

BANKREF_EXTERN(NPCgirl)

extern const palette_color_t NPCgirl_palettes[4];
extern const uint8_t NPCgirl_tiles[416];

extern const metasprite_t* const NPCgirl_metasprites[12];

#endif
