//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_NPCNun_H
#define METASPRITE_NPCNun_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define NPCNun_TILE_ORIGIN 0
#define NPCNun_TILE_W 8
#define NPCNun_TILE_H 8
#define NPCNun_WIDTH 16
#define NPCNun_HEIGHT 16
#define NPCNun_TILE_COUNT 20
#define NPCNun_PALETTE_COUNT 1
#define NPCNun_COLORS_PER_PALETTE 4
#define NPCNun_TOTAL_COLORS 4
#define NPCNun_PIVOT_X 8
#define NPCNun_PIVOT_Y 8
#define NPCNun_PIVOT_W 0
#define NPCNun_PIVOT_H 0

BANKREF_EXTERN(NPCNun)

extern const palette_color_t NPCNun_palettes[4];
extern const uint8_t NPCNun_tiles[320];

extern const metasprite_t* const NPCNun_metasprites[9];

#endif
