//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_NPCPriest_H
#define METASPRITE_NPCPriest_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define NPCPriest_TILE_ORIGIN 0
#define NPCPriest_TILE_W 8
#define NPCPriest_TILE_H 8
#define NPCPriest_WIDTH 16
#define NPCPriest_HEIGHT 16
#define NPCPriest_TILE_COUNT 25
#define NPCPriest_PALETTE_COUNT 1
#define NPCPriest_COLORS_PER_PALETTE 4
#define NPCPriest_TOTAL_COLORS 4
#define NPCPriest_PIVOT_X 8
#define NPCPriest_PIVOT_Y 8
#define NPCPriest_PIVOT_W 0
#define NPCPriest_PIVOT_H 0

BANKREF_EXTERN(NPCPriest)

extern const palette_color_t NPCPriest_palettes[4];
extern const uint8_t NPCPriest_tiles[400];

extern const metasprite_t* const NPCPriest_metasprites[12];

#endif
