//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_NPCScientist_H
#define METASPRITE_NPCScientist_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define NPCScientist_TILE_ORIGIN 0
#define NPCScientist_TILE_W 8
#define NPCScientist_TILE_H 8
#define NPCScientist_WIDTH 16
#define NPCScientist_HEIGHT 16
#define NPCScientist_TILE_COUNT 24
#define NPCScientist_PALETTE_COUNT 1
#define NPCScientist_COLORS_PER_PALETTE 4
#define NPCScientist_TOTAL_COLORS 4
#define NPCScientist_PIVOT_X 8
#define NPCScientist_PIVOT_Y 8
#define NPCScientist_PIVOT_W 0
#define NPCScientist_PIVOT_H 0

BANKREF_EXTERN(NPCScientist)

extern const palette_color_t NPCScientist_palettes[4];
extern const uint8_t NPCScientist_tiles[384];

extern const metasprite_t* const NPCScientist_metasprites[12];

#endif
