//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_StartSprite_H
#define METASPRITE_StartSprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define StartSprite_TILE_ORIGIN 10
#define StartSprite_TILE_W 8
#define StartSprite_TILE_H 8
#define StartSprite_WIDTH 40
#define StartSprite_HEIGHT 16
#define StartSprite_TILE_COUNT 10
#define StartSprite_PALETTE_COUNT 1
#define StartSprite_COLORS_PER_PALETTE 4
#define StartSprite_TOTAL_COLORS 4
#define StartSprite_PIVOT_X 20
#define StartSprite_PIVOT_Y 8
#define StartSprite_PIVOT_W 0
#define StartSprite_PIVOT_H 0

BANKREF_EXTERN(StartSprite)

extern const palette_color_t StartSprite_palettes[4];
extern const uint8_t StartSprite_tiles[160];

extern const metasprite_t* const StartSprite_metasprites[1];

#endif
